version: '3.4'

services:
  chavah.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44363
      - DbConnection_Url=http://chavah.ravendb:8080
      - DbConnection_DatabaseName=ChavahDb
      - DbConnection_FileName=ChavahDb.ravendbdump
      # Fix for docker ssl issue please update password from
      # Manage UserSecrets "Kestrel:Certificates:Development:Password": "a20a8833-d0a8-48c8-b1ab-5a4807355c27"
#      - Kestrel_Certificates_Development_Password=c9b7e1c3-1564-4d7d-85ea-3455587a330d
#      - Kestrel_Certificates_Default_Password=c9b7e1c3-1564-4d7d-85ea-3455587a330d
#      - Kestrel_Certificates_Default_Path=/root/.aspnet/https/Chavah.NetCore.pfx
    ports:
      - "5600:80"
      - "44363:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # https://github.com/ravendb/ravendb/tree/v4.1/docker
  chavah.ravendb:
    environment:
    - RAVEN_Setup_Mode=None
    - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
    - RAVEN_License_Eula_Accepted=true
    - RAVEN_ARGS="--log-to-console"
    ports:
      - "8181:8080"
      - "38888:38888"


  chavah.mail:
    image: mailhog/mailhog
    ports:
     - "8025:8025"
     - "1125:1025"